version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 20
  assignees:
  - xtermi2
  ignore:
  - dependency-name: org.apache.wicket:*
    update-types: [ "version-update:semver-major" ]
  - dependency-name: org.hibernate.validator:hibernate-validator
    update-types: [ "version-update:semver-major" ]
  - dependency-name: org.springframework.data:spring-data-releasetrain
    versions:
    - Kay-x
  - dependency-name: org.springframework.data:spring-data-releasetrain
    versions:
    - Lovelace-x
  - dependency-name: org.wicketstuff:*
    update-types: [ "version-update:semver-major" ]
- package-ecosystem: maven
  directory: "/backend"
  schedule:
    interval: weekly
    time: "02:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 20
  assignees:
  - xtermi2
