version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    default_assignees:
      - "xtermi2"
    ignored_updates:
      - match:
          dependency_name: "org.springframework.data:spring-data-releasetrain"
          version_requirement: "Lovelace-x"
      - match:
          dependency_name: "org.springframework.data:spring-data-releasetrain"
          version_requirement: "Kay-x"
      - match:
          dependency_name: "org.apache.wicket:wicket-core"
          version_requirement: "9.x"
      - match:
          dependency_name: "org.apache.wicket:wicket-extensions"
          version_requirement: "9.x"
      - match:
          dependency_name: "org.apache.wicket:wicket-spring"
          version_requirement: "9.x"
      - match:
          dependency_name: "org.apache.wicket:wicket-auth-roles"
          version_requirement: "9.x"
      - match:
          dependency_name: "org.apache.wicket:wicket-datetime"
          version_requirement: "9.x"
      - match:
          dependency_name: "org.apache.wicket:wicket-bean-validation"
          version_requirement: "9.x"
      - match:
          dependency_name: "org.apache.wicket:wicketstuff-lazymodel"
          version_requirement: "9.x"
      - match:
          dependency_name: "org.apache.wicket:wicketstuff-restannotations"
          version_requirement: "9.x"
      - match:
          dependency_name: "org.apache.wicket:wicketstuff-restannotations-json"
          version_requirement: "9.x"
      - match:
          dependency_name: "org.apache.wicket:wicketstuff-gae-initializer"
          version_requirement: "9.x"
      - match:
          # ignore hibernate-validator 7.x because it's not compatible with wicket 8.x
          dependency_name: "org.hibernate.validator:hibernate-validator"
          version_requirement: "7.x"
  - package_manager: "java:maven"
    directory: "/backend/"
    update_schedule: "daily"
    default_assignees:
      - "xtermi2"