version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "org.springframework.data:spring-data-releasetrain"
          version_requirement: "Lovelace-x"
      - match:
          dependency_name: "org.springframework.data:spring-data-releasetrain"
          version_requirement: "Kay-x"
  - package_manager: "java:maven"
      directory: "/backend/"
      update_schedule: "daily"