name: afrika-run-backend (GCR)

on: [push]

defaults:
  run:
    working-directory: ./backend
  env:
    DOCKER_REGISTY: eu.gcr.io
    PROJECT_ID: ${{ secrets.GCR_PROJECT_ID }}
    RUN_REGION: europe-west1
    CONTAINER_NAME: virtual-run-backend
    GCR_SERVICE_NAME: afrika-run
    MONGODB_USER: ${{ secrets.MONGODB_USER }}
    MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}

jobs:
  build:
    name: Build - Push - Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
          with:
            version: '286.0.0'
            service_account_email: ${{ secrets.GOOGLE_CLOUD_RUN_SA_EMAIL }}
            service_account_key: ${{ secrets.GOOGLE_CLOUD_RUN_SA_KEY }}
            project_id: ${{ secrets.GCR_PROJECT_ID }}

      - name: Setup gcloud docker auth
        run: gcloud auth configure-docker $DOCKER_REGISTY

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: build and create container with Maven
        run: |-
          ./mvnw clean package \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.group=$PROJECT_ID \
            -Dquarkus.container-image.tag=$GITHUB_SHA \
            -Dquarkus.container-image.registry=$DOCKER_REGISTY

      - name: build, create container and push to docker-registry with Maven
        run: |-
          ./mvnw clean package \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.group=$PROJECT_ID \
            -Dquarkus.container-image.tag=$GITHUB_SHA \
            -Dquarkus.container-image.registry=$DOCKER_REGISTY

      - name: Deploy image to Cloud Run
        run: |-
          gcloud run deploy "$GCR_SERVICE_NAME" \
            --quiet \
            --region="$RUN_REGION" \
            --image="$DOCKER_REGISTY/$PROJECT_ID/$CONTAINER_NAME:$GITHUB_SHA" \
            --platform=managed \
            --allow-unauthenticated \
            --concurrency=20 \
            --cpu=1000m \
            --max-instances=1 \
            --memory=256Mi \
            --port=8080 \
            --timeout=900s

